- name: Add repository keys
  with_list: "{{ rabbitmq_repo_keys }}"
  apt_key:
    url: "{{ item }}"

- name: Add repositories
  with_list: "{{ rabbitmq_repo_entries }}"
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes

- name: Install packages
  notify: rabbitmq restart
  apt:
    name: "{{ rabbitmq_pkgs }}"
    state: latest

- name: Ensure RabbitMQ is up and enable
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
