- name: add rabbitmq endpoint to hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 localhost'
    line: '127.0.0.1 localhost {{ rabbitmq_endpoint }}'
    state: present

- name: Download rabbitmq repository key (remove this on ansible 2.4)
  get_url:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    dest: /tmp/rabbitmq.asc

- name: Add rabbitmq repository key
  apt_key:
    file: /tmp/rabbitmq.asc
    state: present

- name: Add rabbitmq repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present
    update_cache: yes

- name: Install rabbitmq-server package
  apt:
    name: rabbitmq-server
    state: latest

- name: ensure rabbit uses "localhost" as hostname
  register: rabbit_nodename
  lineinfile:
    path: /etc/rabbitmq/rabbitmq-env.conf
    line: 'NODENAME=rabbit@localhost'
    create: yes
    mode: 0644

- name: generate folder for config files
  file:
    path: /etc/rabbitmq/rabbitmq.conf.d
    state: directory
    mode: 0755

- name: Ensure RabbitMQ is restarted and enable
  when: rabbit_nodename.changed
  service:
    name: rabbitmq-server
    state: restarted

- name: Ensure RabbitMQ is up and enable
  service:
    name: rabbitmq-server
    state: started
    enable: yes

- name: enable management
  when: rabbit_enable_management
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: Add rabbitmq user
  rabbitmq_user:
    user: "{{ rabbitmq.user }}"
    password: "{{ rabbitmq.password }}"
    tags: "management"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: "present"

- name: Remove guest user
  rabbitmq_user:
    user: "guest"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: "absent"

- name: service_configuration
  include_tasks: service_configuration.yml
