- name: Add rabbitmq repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Add rabbitmq repository key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present validate_certs=no

- name: Install rabbitmq-server package
  apt: name=rabbitmq-server state=latest update-cache=yes 

- name: Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started enabled=yes

- name: Add rabbitmq user
  rabbitmq_user: user={{ rabbitmq.user }}
                 password={{ rabbitmq.password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
