- name: Download rabbitmq repository key (remove this on ansible 2.4)
  get_url:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    dest: /tmp/rabbitmq.asc

- name: Add rabbitmq repository key
  apt_key:
    file: /tmp/rabbitmq.asc
    state: present

- name: Add rabbitmq repository
  apt_repository:
    repo: "deb http://www.rabbitmq.com/debian/ testing main"
    state: present
    update_cache: yes

- name: Install rabbitmq-server package
  apt:
    name: rabbitmq-server
    state: latest

- name: Ensure RabbitMQ is running
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add rabbitmq user
  rabbitmq_user:
    user: "{{ rabbitmq.user }}"
    password: "{{ rabbitmq.password }}"
    vhost: "/"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: "present"
