- name: check python version
  shell: python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'
  register: pythonversion

- name: install system dependencies for rabbit repo
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - libffi-dev
  - libssl-dev
  - python-dev
  - python-pip
  - build-essential
  when: "{{ pythonversion.stdout | version_compare('2.7.9', '<') }}"

- name: install dependencies for rabbit repo
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - urllib3
  - pyopenssl
  - ndg-httpsclient
  - pyasn1
  when: "{{ pythonversion.stdout | version_compare('2.7.9', '<') }}"


- name: Add rabbitmq repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Add rabbitmq repository key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

- name: Install rabbitmq-server package
  apt: name=rabbitmq-server state=latest update-cache=yes

- name: Add rabbitmq user
  rabbitmq_user: user={{ rabbitmq.user }}
                 password={{ rabbitmq.password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

- name: Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started